name: pyHRMC CI

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
      - test-ci
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the OS for the CI run
    # container:
    #   image: ehrhardtkm/lammps-flare:latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']  # Define the versions of Python to test on
         

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install FLARE
      run: |
        pwd

        sudo apt-get update
        sudo apt-get install -y gcc g++ cmake libomp-dev liblapacke-dev libopenblas-dev


        # git clone https://github.com/mir-group/flare.git
        # cd flare
        # python -m pip install .      
        # pwd  

        git clone git@github.com:mir-group/flare.git
        cd flare
        mkdir build
        cd build
        cmake ..
        cmake --build . -j4

        cp _C_flare*.so ../flare/bffs/sgp
        cd ..

        export PYTHONPATH=${PYTHONPATH}:<current_dir>



    - name: Install LAMMPS in serial
      run: |
        pwd
        ls
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libfftw3-dev libblas-dev liblapack-dev
        git clone -b stable https://github.com/lammps/lammps.git

        cd flare/lammps_plugins/
        pwd
        ls
        pwd ../../
        ls ../../
        ./install.sh ../../lammps/
        
        cd ../../lammps
        pwd
        mkdir build
        cd build
        pwd
        cmake ../cmake  -DBUILD_MPI=OFF  -DPKG_MANYBODY=ON -DPKG_KSPACE=ON -DPKG_MACHDYN=yes -DDOWNLOAD_EIGEN3=yes -D BUILD_SHARED_LIBS=yes 
        make VERBOSE=1 -j4
        make install-python

    - name: Patch ASE
      run: |
        ase_file="$(dirname $(python3 -c 'import ase; print(ase.__file__)'))/calculators/lammpsrun.py"
        sed -i 's/line.startswith(_custom_thermo_mark)/line.strip\(\).startswith\("Step"\)/g' $ase_file

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install .

    - name: Run tests
      run: |
        export lmp=$(pwd)/lammps/build/lmp
        pytest flare/tests
        pytest tests/
        pytest --cov=pyhrmc tests/
